{% set name = "openalea.deploy" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openalea/deploy/archive/v{{ version }}.tar.gz
  sha256: e91910780c4017e2e785be89ade7b76031156691f64d8b057b9dc93594502c52

build:
  number: 0
  script: {{ PYTHON }} setup.py install
  preserve_egg_dir: true

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - path


test:
  imports:
    - openalea.deploy

about:
  home: http://github.com/openalea/deploy
  license: CECILL-C
  license_file: LICENSE
  summary: OpenAlea.Deploy support the installation of OpenAlea packages.

  # The remaining entries in this section are optional, but recommended.
  description: |
    OpenAlea.Deploy support the installation of OpenAlea packages for 
    Python 3.7+. It is an extension of setuptools.
    Features :

      * Install shared libraries, include and libs in eggs
      * Support 'develop' command
      * Call SCons or CMake scripts in setup.py

  dev_url: https://github.com/openalea/deploy

extra:
  recipe-maintainers:
    - pradal
