{% set name = "openalea.deploy" %}
{% set version = "2.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openalea/deploy/archive/v{{ version }}.tar.gz
  sha256: 0508b493a9dcac9577f8e7f0092b91bbc01394243dbcc562b3832d39d8686bb9

build:
  number: 1
  script: "{{ PYTHON }} setup.py install"
  preserve_egg_dir: True

requirements:
  host:
    - python
    - setuptools
    - six
  run:
    - python
    - setuptools
    - pywin32  # [win]
    - six
    - path.py


test:
  imports:
    - openalea.deploy

about:
  home: http://github.com/openalea/deploy
  license: CECILL-C
  license_file: LICENSE
  summary: OpenAlea.Deploy support the installation of OpenAlea packages.

  # The remaining entries in this section are optional, but recommended.
  description: |
    OpenAlea.Deploy support the installation of OpenAlea packages for Python 2.7+ and
    Python 3.3+. It is an extension of setuptools.
    Features :

        Discover and manage packages in EGG format
        Install shared libraries, include and libs in eggs
        Support 'develop' command
        Call SCons or CMake scripts in setup.py
        Create namespaces if necessary

  dev_url: https://github.com/openalea/deploy

extra:
  recipe-maintainers:
    - pradal
    - fredboudon
